def build(bld):
    bld.new_task_gen(
            features='slice2cpp cxx cstaticlib pcgen',
            source='DHCP.ice',
            target='tartarus-slice-DHCP',
            slice_includes='..',
            headers_path='${INCLUDEDIR}/Tartarus/DHCP',
            includes='. ..',
            pc_filename = 'tartarus-slice-dhcp.pc',
            pc_env_defines = 'includedir',
            pc_name = 'tartarus-slice-dhcp',
            pc_description = 'Tartarus library for using DHCP service',
            pc_requires = ['tartarus-slice-core = ${version}'],
            pc_libs = '-ltartarus-slice-dhcp',
            pc_cflags='-I${includedir}/Tartarus')

