def build(bld):
    bld.new_task_gen(
            features='slice2cpp cxx cstaticlib pcgen',
            source='kadmin.ice',
            target='tartarus-slice-Kerberos',
            slice_includes='..',
            headers_path='${INCLUDEDIR}/Tartarus/Kerberos',
            includes='. ..',
            pc_filename = 'tartarus-slice-kerberos.pc',
            pc_env_defines = 'includedir',
            pc_name = 'tartarus-slice-kerberos',
            pc_description = 'Tartarus library for using Kerberos service',
            pc_requires = ['tartarus-slice-core = ${version}'],
            pc_libs = '-ltartarus-slice-kerberos',
            pc_cflags='-I${includedir}/Tartarus')

