
def build(bld):
    bld.new_task_gen(
            features='py',
            source=bld.glob('*.py'),
            install_path='${LIBDIR}/Tartarus/modules/DHCP')
    bld.install_files('${LIBDIR}/Tartarus/modules/DHCP', 'dhcpd_conf.tmpl')

