def build(bld):
    bld.new_task_gen(
            features='slice2cpp cxx cstaticlib pcgen',
            source=bld.glob('*.ice'),
            target='tartarus-slice-core',
            slice_includes='..',
            headers_path='${INCLUDEDIR}/Tartarus/core',
            includes='. ..',
            pc_filename = 'tartarus-slice-core.pc',
            pc_env_defines = 'includedir',
            pc_name = 'tartarus-slice-core',
            pc_description = 'Tartarus slice core library',
            pc_libs = '-ltartarus-slice-core',
            pc_cflags='-I${includedir}/Tartarus')

